### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by meljeans** [robtarr/website#1]
I believe "seesparkbox.com" should point to:

http://seesparkbox.com/foundry/author/rob_tarr

It errors now 😄 

![screen shot 2016-05-06 at 3 52 22 pm](https://cloud.githubusercontent.com/assets/1264616/15084628/bd9cc5ba-13a2-11e6-93af-d230bda05c23.png)

**Comment by robtarr** [comment]
![barney-fife](https://cloud.githubusercontent.com/assets/270461/15100765/cd830f62-154a-11e6-9388-8dfbec9eec91.gif)
